name: portfolio_flutter_blockchain_medical_web_app
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.1.0
  logger: ^2.1.0
  flutter_riverpod: ^1.0.4
  skeletons: ^0.0.3
  go_router: ^13.2.0
  badges: ^3.1.2
  uuid: ^4.3.2
  debounce_throttle: ^2.0.0

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  expandable_text: ^2.3.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.0.0

  intl: ^0.17.0

  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  firebase_database: ^10.0.15
  http: ^1.2.0
  timezone: ^0.9.3
  get_it: ^7.6.7
  local_notifier: ^0.1.6
dev_dependencies:
  drift_dev: ^2.14.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2

flutter:
  assets:
    - asset/img/food/
    - asset/img/logo/
    - asset/img/misc/
    - asset/svg/icon/
    - asset/rive/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100
  uses-material-design: true